os:
  - linux
  - osx

language: generic
sudo: required
dist: trusty
osx_image: xcode9

install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"

script:
  - swift test --parallel

after_success:
  - bash <(curl -s https://codecov.io/bash)
