language: generic

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
    - os: osx
      osx_image: xcode9.3

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get update;
      sudo apt-get install swift;
    fi
  - swift --version

script:
  - swift test --parallel

after_success:
  - bash <(curl -s https://codecov.io/bash)
